loja/product/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = "product"

urlpatterns = [
    path("", views.ProductListView.as_view(), name="list"),
    path("<slug>", views.ProductDetailView.as_view(), name="detail"),
    path("add-to-cart/", views.AddToCart.as_view(), name="addtocart"),
    path(
        "remove-from-cart/<vid>", views.RemoveFromCart.as_view(), name="removefromcart"
    ),
    path("cart/", views.Cart.as_view(), name="cart"),
    path("checkout/", views.Checkout.as_view(), name="checkout"),
]

loja/urls.py
# -*- coding: utf-8 -*-
"""loja URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path("", include("loja.product.urls")),
    path("profile", include("loja.profile.urls")),
    path("order", include("loja.order.urls")),
    path("admin/", admin.site.urls),
]
# urlpatterns = i18n_patterns(
#     path("", include("loja.product.urls")),
#     path("profile", include("loja.profile.urls")),
#     path("order", include("loja.order.urls")),
#     path("admin/", admin.site.urls),
# )

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

loja/product/models.py
# -*- coding: utf-8 -*-
import sys
from io import BytesIO

from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from PIL import Image


class Product(models.Model):
    VARIABLE = 1
    SIMPLE = 2
    TYPE = ((VARIABLE, _("Variable")), (SIMPLE, _("Simple")))

    product_name = models.CharField(_("product name"), max_length=100)
    short_description = models.TextField(_("short description"), max_length=255)
    long_description = models.TextField(_("long description"))
    image = models.ImageField(
        _("image"), upload_to="images/products/", blank=True, null=True
    )
    slug = models.SlugField(_("slug"), unique=True, blank=True)
    price = models.DecimalField(_("price"), max_digits=6, decimal_places=2)
    promo_price = models.DecimalField(
        _("promotional price"), max_digits=6, decimal_places=2
    )
    type = models.PositiveSmallIntegerField(_("type"), choices=TYPE, default=SIMPLE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("product")
        verbose_name_plural = _("products")
        ordering = ("-created_at",)

    def __str__(self):
        return self.product_name

    def save(self, *args, **kwargs):
        max_image_size = 800
        if self.image:
            self.image = self.resize_image(self.image, max_image_size)

        if not self.slug:
            self.slug = slugify(self.product_name)

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("product", kwargs={"pk": self.pk})

    @staticmethod
    def resize_image(image, max_image_size=800):
        img_pil = Image.open(image)
        original_width, original_height = img_pil.size
        if original_width <= max_image_size:
            return image

        output = BytesIO()
        new_height = round(original_height * max_image_size / original_width)
        resized_img = img_pil.resize((max_image_size, new_height), Image.LANCZOS)
        resized_img.save(output, format=img_pil.format, optimize=True, quality=80)
        output.seek(0)
        return InMemoryUploadedFile(
            output,
            "ImageField",
            image.name,
            img_pil.format,
            sys.getsizeof(output),
            None,
        )


class Variation(models.Model):
    product = models.ForeignKey(
        verbose_name=_("product"),
        to=Product,
        on_delete=models.CASCADE,
    )
    variation_name = models.CharField(_("name"), max_length=50, blank=True, null=True)
    price = models.DecimalField(_("price"), max_digits=6, decimal_places=2)
    promo_price = models.DecimalField(
        _("promotional price"), max_digits=6, decimal_places=2, blank=True, null=True
    )
    stock = models.PositiveIntegerField(_("stock"), default=0)

    class Meta:
        ordering = ("-price",)
        verbose_name_plural = _("variations")
        verbose_name = _("variation")

    def __str__(self):
        return self.variation_name or self.product.product_name

    def get_price(self):
        if self.promo_price > 0:
            return self.promo_price
        else:
            return self.price

loja/product/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render, reverse
from django.utils.text import format_lazy
from django.utils.translation import gettext as _
from django.views import View
from django.views.generic import DetailView, ListView

from .models import Product, Variation


class ProductListView(ListView):
    model = Product
    context_object_name = "products"
    paginate_by = 12


class ProductDetailView(DetailView):
    model = Product
    context_object_name = "product"
    slug_url_kwarg = "slug"


class AddToCart(View):
    def get(self, *args, **kwargs):
        # del self.request.session["cart"]
        # self.request.session.save()

        referer = self.request.META.get("HTTP_REFERER", reverse("product:list"))
        var_id = self.request.GET.get("vid")
        if not var_id:
            messages.error(self.request, _("product doesn't exist").capitalize())
            return redirect(referer)
        var = get_object_or_404(Variation, id=var_id)
        var_stock = var.stock
        product = var.product
        product_id = product.id
        product_name = product.product_name
        variation_name = var.variation_name or ""
        variation_id = var.id
        unit_price = var.price
        unit_price_promo = var.promo_price or None
        total_price = var.price
        total_price_promo = var.promo_price or None
        quantity = 1
        slug = product.slug
        image = product.image

        if not self.request.session.get("cart"):
            self.request.session["cart"] = {}
            self.request.session.save()

        cart = self.request.session["cart"]

        if var.stock < 1:
            messages.error(self.request, _("not enough stock").capitalize())
            return redirect(referer)

        if var_id in cart:
            cart_qty = cart[var_id]["quantity"]
            cart_qty += 1
            if var_stock < cart_qty:
                str1 = _("not enought stock for").capitalize()
                str2 = _("added")
                str3 = _("items")
                messages.warning(
                    self.request,
                    format_lazy(
                        "{} {} {} {}, {} {} {}",
                        str1,
                        cart_qty,
                        product_name,
                        variation_name,
                        str2,
                        var_stock,
                        str3,
                    ),
                )
                cart_qty = var_stock
            cart[var_id]["quantity"] = cart_qty
            cart[var_id]["total_price"] = cart_qty * unit_price
            cart[var_id]["total_price_promo"] = (
                unit_price_promo * cart_qty if unit_price_promo is not None else None
            )

        else:
            cart[var_id] = {
                "product_id": product_id,
                "product_name": product_name,
                "variation_name": variation_name,
                "variation_id": variation_id,
                "unit_price": unit_price,
                "unit_price_promo": unit_price_promo,
                "total_price": total_price,
                "total_price_promo": total_price_promo,
                "quantity": quantity,
                "slug": slug,
                "image": image,
            }
        self.request.session.save()
        str1 = _("product").capitalize()
        str2 = _("added to cart")
        messages.success(
            self.request,
            format_lazy("{} {} {} {}", str1, product_name, variation_name, str2),
        )
        return redirect(referer)


class RemoveFromCart(View):
    def get(self, *args, **kwargs):
        var_id = kwargs.get("vid")
        referer = self.request.META.get("HTTP_REFERER", reverse("product:list"))
        cart = self.request.session["cart"]
        if not var_id or var_id not in cart:
            return redirect(referer)

        str1 = _("product").capitalize()
        str2 = _("removed from cart")
        messages.success(
            self.request,
            format_lazy(
                "{} {} {} {}",
                str1,
                cart[var_id]["product_name"],
                cart[var_id]["variation_name"],
                str2,
            ),
        )
        del cart[var_id]
        self.request.session.save()
        return redirect(referer)


class Cart(View):
    def get(self, *args, **kwargs):
        return render(self.request, "product/cart.html")


class Checkout(View):
    pass

loja/product/templates/product/cart.html
{% extends "base.html" %}
{% load i18n %}
{% load filters %}
{% block content %}
    <div class="row mt-3">
        <div class="col">
            <h3>{{ _("shoping cart") | title }}</h3>
            {% if request.session.cart %}
                <p class="lead">
                    {{ _("items added to cart") | capfirst }}
                </p>
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <th class="d-none d-lg-block">{{ _("image") | title }}</th>
                            <th>{{ _("product") | title }}</th>
                            <th>{{ _("variation") | title }}</th>
                            <th>{{ _("quantity") | title }}</th>
                            <th>{{ _("total") | title }}</th>
                            <th>{{ _("price") | title }}</th>
                            <th>{{ _("promotional price") | title }}</th>
                        </tr>
                        {% for product in request.session.cart.values %}
                            <tr>
                                <td class="d-none d-lg-block">
                                    <a href="{% url 'product:detail' product.slug %}" class="link-primary">
                                        <img class="cart-img"
                                             src="{{ product.image.url }}"
                                             alt="alt"
                                             width="100%"
                                             height="100%"/>
                                    </a>
                                </td>
                                <td>
                                    <a href="{% url 'product:detail' product.slug %}" class="link-primary">{{ product.product_name }}</a>
                                    <a class="ml-3"
                                       href="{% url 'product:removefromcart' product.variation_id %}">
                                        <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                                    </a>
                                </td>
                                <td>{{ product.variation_name }}</td>
                                <td>{{ product.quantity }}</td>
                                <td>{{ product.total_price_promo | default:product.total_price | currency }}</td>
                                <td>{{ product.total_price | currency }}</td>
                                <td>{{ product.total_price_promo | currency }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% else %}
                <p class="lead">
                    {{ _("your cart is empty") | capfirst }}
                </p>
            {% endif %}
        </div>
    </div>
    {% if request.session.cart %}
        <div class="row mt-3">
            <div class="col-lg">
                <p class="lead">
                    {{ _("subtotal") | title }}
                </p>
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <td class="font-weight-bold">{{ _("subtotal") | capfirst }}</td>
                            <td>{{ request.session.cart| total_value | currency }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="col-lg mt-auto">
                <a class="btn btn-lg btn-block btn-primary" href="#">{{ _("checkout") | title }}</a>
            </div>
        </div>
    {% endif %}
{% endblock content %}

loja/product/templates/product/product_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load l10n %}
{% load crispy_forms_tags %}
{% load humanize %}
{% load filters %}
{% block title %}
    {{ product.product_name | title }}
{% endblock title %}
{% block content %}
    <div class="row">
        <div class="col-lg">
            <div class="row no-gutters">
                <div class="col-lg-12">
                    {% if product.image %}
                        <img class="img-fluid"
                             src="{{ product.image.url }}"
                             width="100%"
                             height="100%"
                             alt="{{ product.product_name }}"/>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg">
            <div class="mt-4 mt-lg-0">
                <h1 class="h2">{{ product.product_name }}</h1>
                <p class="lead">
                    {{ product.short_description }}
                </p>
                <p class="lead">
                    {% if product.promo_price %}
                        <span id="var-scratched-price" class="lead product-old-price mask-money">{{ product.price | currency }}</span>
                        <span id="var-effective-price" class="lead product-price mask-money">{{ product.promo_price | currency }}</span>
                    {% else %}
                        <span id="var-scratched-price"
                              class="lead product-price text-muted mask-money">{{ product.price | currency }}</span>
                    </div>
                    <span id="var-effective-price"
                          class="lead product-price text-muted mask-money">{{ product.price | currency }}</span>
                {% endif %}
            </p>
        </div>
        <form action="{% url 'product:addtocart' %}" id="form-add-to-cart">
            <div class="form-group">
                <select id="select-variation" name="vid" class="form-control form-control-lg">
                    {% for var in product.variation_set.all %}
                        <option data-price="{{ var.price | default_if_none:0 }}"
                                data-promotional-price="{{ var.promo_price | default_if_none:0 }}"
                                value="{{ var.id }}">
                            {{ var }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div class="text-left">
                <button type="submit" class="btn btn-primary btn-lg btn-block">
                    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    Adicionar ao carrinho
                </button>
            </div>
        </form>
    </div>
</div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="mt-5 mb-5">
            <h2 class="text-center">{{ product.product_name }}</h2>
            <p>
                {{ product.long_description | linebreaks }}
            </p>
        </div>
    </div>
</div>
{% endblock content %}

loja/product/templates/product/product_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load filters %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card-columns">
                {% for product in products %}
                    <div class="card">
                        {% if product.image %}
                            <a href="{{ product.slug }}">
                                <img class="card-img-top"
                                     src="{{ product.image.url }}"
                                     alt="{{ product.name }}"
                                     height="100%"
                                     width="100%"/>
                            </a>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ product.product_name }}</h5>
                            <p class="card-text">
                                {{ product.short_description | truncatechars:100 }}
                            </p>
                            <div class="container product-price-block text-center">
                                {% if product.promo_price %}<span class="product-old-price text-muted">{{ product.price | currency }}</span>{% endif %}
                                <span class="product-price">{{ product.price | currency }}</span>
                            </div>
                        </div>
                        <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <a href="post.html" class="btn btn-primary btn-sm m-1 btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Comprar
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class"col">{% include "partial/_pagination.html" %}</div>
    </div>
{% endblock content %}